language: php

php:
  - 5.2

before_script:
  - git clone --depth=100 https://github.com/yiisoft/yii.git yii

script: phpunit --colors --coverage-text --include-path ./yii/framework tests/controllers/SlugControllerTest.php
