language: php

php:
  - 5.2

before_script:
  - git clone --depth=100 https://github.com/yiisoft/yii.git yii

script: phpunit --include-path ./yii/framework --configuration ./tests/phpunit.xml.dist tests/controllers/SlugControllerTest.php
